local env = select(2, ...)
local UIKit = env.WPM:Import("wpm_modules\\ui-kit")
local GenericEnum = env.WPM:New("wpm_modules\\generic-enum")

GenericEnum.UIColorRGB = {
    Normal                          = UIKit.Define.Color_RGBA{ r = 255, g = 209, b = 0, a = 1 },
    White                           = UIKit.Define.Color_RGBA{ r = 255, g = 255, b = 255, a = 1 },
    Highlight                       = UIKit.Define.Color_RGBA{ r = 255, g = 255, b = 255, a = 1 },
    Red                             = UIKit.Define.Color_RGBA{ r = 255, g = 26, b = 26, a = 1 },
    DimRed                          = UIKit.Define.Color_RGBA{ r = 204, g = 26, b = 26, a = 1 },
    DullRed                         = UIKit.Define.Color_RGBA{ r = 191, g = 38, b = 38, a = 1 },
    Green                           = UIKit.Define.Color_RGBA{ r = 26, g = 255, b = 26, a = 1 },
    Gray                            = UIKit.Define.Color_RGBA{ r = 128, g = 128, b = 128, a = 1 },
    Yellow                          = UIKit.Define.Color_RGBA{ r = 255, g = 255, b = 0, a = 1 },
    LightYellow                     = UIKit.Define.Color_RGBA{ r = 255, g = 255, b = 153, a = 1 },
    Orange                          = UIKit.Define.Color_RGBA{ r = 255, g = 128, b = 64, a = 1 },
    PassiveSpell                    = UIKit.Define.Color_RGBA{ r = 196, g = 163, b = 0, a = 1 },
    BattleNet                       = UIKit.Define.Color_RGBA{ r = 130, g = 197, b = 255, a = 1 },
    Transmogrify                    = UIKit.Define.Color_RGBA{ r = 255, g = 128, b = 255, a = 1 },
    Disabled                        = UIKit.Define.Color_RGBA{ r = 127, g = 127, b = 127, a = 1 },
    Blue                            = UIKit.Define.Color_RGBA{ r = 0, g = 191, b = 243, a = 1 },
    LightBlue                       = UIKit.Define.Color_RGBA{ r = 135, g = 171, b = 255, a = 1 },
    LightGray                       = UIKit.Define.Color_RGBA{ r = 153, g = 153, b = 153, a = 1 },
    DimGreen                        = UIKit.Define.Color_RGBA{ r = 64, g = 192, b = 64, a = 1 },
    Black                           = UIKit.Define.Color_RGBA{ r = 0, g = 0, b = 0, a = 1 },
    Link                            = UIKit.Define.Color_RGBA{ r = 102, g = 187, b = 255, a = 1 },
    QuestObjective                  = UIKit.Define.Color_RGBA{ r = 204, g = 204, b = 204, a = 1 },
    QuestOBjectiveHighlight         = UIKit.Define.Color_RGBA{ r = 255, g = 255, b = 255, a = 1 },
    QuestObjectiveDisabled          = UIKit.Define.Color_RGBA{ r = 127, g = 127, b = 127, a = 1 },
    QuestObjectiveDisabledHighlight = UIKit.Define.Color_RGBA{ r = 153, g = 153, b = 153, a = 1 },
    AreaName                        = UIKit.Define.Color_RGBA{ r = 255, g = 237, b = 194, a = 1 },
    AreaDescription                 = UIKit.Define.Color_RGBA{ r = 255, g = 255, b = 255, a = 1 },
    Invasion                        = UIKit.Define.Color_RGBA{ r = 199, g = 255, b = 0, a = 1 },
    InvasionDescription             = UIKit.Define.Color_RGBA{ r = 255, g = 248, b = 9, a = 1 }
}

GenericEnum.ColorRGB01 = {
    Normal                          = { r = 1, g = 0.82, b = 0 },
    White                           = { r = 1, g = 1, b = 1 },
    Highlight                       = { r = 1, g = 1, b = 1 },
    Red                             = { r = 1, g = 0.1, b = 0.1 },
    DimRed                          = { r = 0.8, g = 0.1, b = 0.1 },
    DullRed                         = { r = 0.75, g = 0.15, b = 0.15 },
    Green                           = { r = 0.1, g = 1, b = 0.1 },
    Gray                            = { r = 0.5, g = 0.5, b = 0.5 },
    Yellow                          = { r = 1, g = 1, b = 0 },
    LightYellow                     = { r = 1, g = 1, b = 0.6 },
    Orange                          = { r = 1, g = 0.5, b = 0.25 },
    PassiveSpell                    = { r = 0.77, g = 0.64, b = 0 },
    BattleNet                       = { r = 0.510, g = 0.773, b = 1 },
    Transmogrify                    = { r = 1, g = 0.5, b = 1 },
    Disabled                        = { r = 0.498, g = 0.498, b = 0.498 },
    Blue                            = { r = 0, g = 0.749, b = 0.952 },
    LightBlue                       = { r = 0.53, g = 0.67, b = 1 },
    LightGray                       = { r = 0.6, g = 0.6, b = 0.6 },
    DimGreen                        = { r = 0.251, g = 0.753, b = 0.251 },
    Black                           = { r = 0, g = 0, b = 0 },
    Link                            = { r = 102 / 255, g = 187 / 255, b = 1 },
    QuestObjective                  = { r = 0.8, g = 0.8, b = 0.8 },
    QuestOBjectiveHighlight         = { r = 1, g = 1, b = 1 },
    QuestObjectiveDisabled          = { r = 0.498, g = 0.498, b = 0.498 },
    QuestObjectiveDisabledHighlight = { r = 0.6, g = 0.6, b = 0.6 },
    AreaName                        = { r = 1, g = 0.9294, b = 0.7607 },
    AreaDescription                 = { r = 1, g = 1, b = 1 },
    Invasion                        = { r = 0.78, g = 1, b = 0 },
    InvasionDescription             = { r = 1, g = 0.973, b = 0.035 }
}

GenericEnum.ColorRGB255 = {
    Normal                          = { r = 255, g = 209, b = 0 },
    White                           = { r = 255, g = 255, b = 255 },
    Highlight                       = { r = 255, g = 255, b = 255 },
    Red                             = { r = 255, g = 26, b = 26 },
    DimRed                          = { r = 204, g = 26, b = 26 },
    DullRed                         = { r = 191, g = 38, b = 38 },
    Green                           = { r = 26, g = 255, b = 26 },
    Gray                            = { r = 128, g = 128, b = 128 },
    Yellow                          = { r = 255, g = 255, b = 0 },
    LightYellow                     = { r = 255, g = 255, b = 153 },
    Orange                          = { r = 255, g = 128, b = 64 },
    PassiveSpell                    = { r = 196, g = 163, b = 0 },
    BattleNet                       = { r = 130, g = 197, b = 255 },
    Transmogrify                    = { r = 255, g = 128, b = 255 },
    Disabled                        = { r = 127, g = 127, b = 127 },
    Blue                            = { r = 0, g = 191, b = 243 },
    LightBlue                       = { r = 135, g = 171, b = 255 },
    LightGray                       = { r = 153, g = 153, b = 153 },
    DimGreen                        = { r = 64, g = 192, b = 64 },
    Black                           = { r = 0, g = 0, b = 0 },
    Link                            = { r = 102, g = 187, b = 255 },
    QuestObjective                  = { r = 204, g = 204, b = 204 },
    QuestOBjectiveHighlight         = { r = 255, g = 255, b = 255 },
    QuestObjectiveDisabled          = { r = 127, g = 127, b = 127 },
    QuestObjectiveDisabledHighlight = { r = 153, g = 153, b = 153 },
    AreaName                        = { r = 255, g = 237, b = 194 },
    AreaDescription                 = { r = 255, g = 255, b = 255 },
    Invasion                        = { r = 199, g = 255, b = 0 },
    InvasionDescription             = { r = 255, g = 248, b = 9 }
}

GenericEnum.ColorHEX = {
    Normal                          = "|cffffd100",
    White                           = "|cffffffff",
    Highlight                       = "|cffffffff",
    Red                             = "|cffff1a1a",
    DimRed                          = "|cffcc1a1a",
    DullRed                         = "|cffbf2626",
    Green                           = "|cff1aff1a",
    Gray                            = "|cff808080",
    Yellow                          = "|cffffff00",
    LightYellow                     = "|cffffff99",
    Orange                          = "|cffff8040",
    PassiveSpell                    = "|cffc4a300",
    BattleNet                       = "|cff82c5ff",
    Transmogrify                    = "|cffff80ff",
    Disabled                        = "|cff7f7f7f",
    Blue                            = "|cff00bff3",
    LightBlue                       = "|cff87abff",
    LightGray                       = "|cff999999",
    DimGreen                        = "|cff40c040",
    Black                           = "|cff000000",
    Link                            = "|cff66bbff",
    QuestObjective                  = "|cffcccccc",
    QuestOBjectiveHighlight         = "|cffffffff",
    QuestObjectiveDisabled          = "|cff7f7f7f",
    QuestObjectiveDisabledHighlight = "|cff999999",
    AreaName                        = "|cffffedc2",
    AreaDescription                 = "|cffffffff",
    Invasion                        = "|cffc7ff00",
    InvasionDescription             = "|cfffff809"
}
